
spring:
  application:
    name: creditcard-microservice
  config:
    import: optional:configserver:${CONFIG_SERVER_URL:http://localhost:8888/}
  profiles:
    active: dev
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

