
spring:
  application:
    name: creditcard-microservice
  config:

    import: optional:configserver:${BUILD_IN_SPRING_CLOUD_CONFIG_URI:http://localhost:8888/}


  profiles:
    active: dev
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

