
spring:
  application:
    name: creditcard-microservice
  config:
    import: optional:configserver:http://localhost:8888
  profiles:
    active: dev
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

microservices-urls:
  api-client: http://localhost:8095/api/client